name: DevOps
on:
  workflow_dispatch:
jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Teste antes descrypt
         run: cat .env
       - name: Decrypt secrets file
         env:
           VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
         run: |
           ansible-vault decrypt secrets.yml --vault-password-file <(echo $VAULT_PASSWOR)
       - name: Teste depois descrypt
         run: cat .env