name: DevOps
on:
  workflow_dispatch:

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}
    steps:
      - name: Check branch and set environment
        id: set-environment
        run: |
           echo "BRANCH = $GITHUB_REF_NAME"
           if [ "$GITHUB_REF_NAME" == "master" ]; then
           echo "environment=prd" >> $GITHUB_OUTPUT
           else
           echo "environment=dev" >> $GITHUB_OUTPUT
           fi
           echo "Environment is set to: ${{ env.environment }}"
      - name: Use the output value
        run: |
         echo "The greeting is: ${{ steps.set-environment.outputs.environment }}"

  deploy:
     runs-on: ubuntu-latest
     needs: set-environment
     environment: ${{ needs.set-environment.outputs.environment }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Print environment
         run: |
          echo "Ambiente selecionado: ${{ needs.set-environment.outputs.environment }}"

           
       - name: Checkout
         uses: actions/checkout@v3

       - name: Authentication AWS
         uses: aws-actions/configure-aws-credentials@v2
         with:
           aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}_{1}', vars.AWS_ACCOUNT, needs.set-environment.outputs.environment)] }}
           aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}_{1}', vars.AWS_ACCOUNT, needs.set-environment.outputs.environment)] }}
           aws-region: ${{ vars.REGION }}
      
       - name: Upload App in S3 Bucket
         run: aws s3 ls

       - name: Upload App in S3 Bucket
         run: |
           aws s3 sync --no-follow-symlinks . s3://${{ vars.BUCKET_NAME }}/

       - name: Invalidate App Cache
         run: |
           # Invalidate App Cache
           echo "Iniciando limpeza de cache no cloudfront: ${{ vars.DISTRIBUTION_ID }}"
           aws cloudfront create-invalidation --distribution-id ${{ vars.DISTRIBUTION_ID }} --paths "/*"
      