name: DevOps
on:
  workflow_dispatch:

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}"
    steps:
      - name: Check branch and set environment
        id: set-environment
        run: |
           echo "BRANCH RECEBIDA: $GITHUB_REF_NAME"
           if [ "$GITHUB_REF_NAME" == "master" ]; then
           echo "environment=prd" >> $GITHUB_OUTPUT
           else
           echo "environment=dev" >> $GITHUB_OUTPUT
           fi
           echo "Environment is set to: ${{ env.environment}}"
      - name: Use the output value
        run: |
         echo "The greeting is: ${{ steps.set-environment.outputs.environment }}"
  deploy:
     runs-on: ubuntu-latest
     needs: set-environment
     steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Print environment
         run: |
          echo "Ambiente selecionado: ${{ needs.set-environment.outputs.environment }}"