name: DevOps
on:
  workflow_dispatch:

jobs:
  environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.environment }}
    steps:
      - name: Check branch and set environment
        run: |
           echo "BRANCH RECEBIDA: $GITHUB_REF_NAME"
           if [ "$GITHUB_REF_NAME" == "master" ]; then
           echo "environment=prd" >> $GITHUB_ENV
           else
           echo "environment=dev" >> $GITHUB_ENV
           fi
           echo "Environment is set to: ${{ env.environment}}"